[workspace]

members = [
    "primitives",
    "splines",
    "render",
    "brep",
    "viewer",
    "tessellate",
    "components",
    "examples/curve_arc",
    "examples/curve_bezier_decomposition",
    "examples/curve_knot_refinement",
    "examples/curve_nearest_point",
    "examples/curve_interpolate_half_circle",
    "examples/curve_point_projection",
    "examples/curve_point_inversion",
    "examples/curve_interpolate_ders_half_circle",
    "examples/surface_skinned_curves",
    "examples/surface_knot_refinement",
    "examples/surface_ruled_curve",
    "examples/surface_swept_curve",
]
