[package]
name = "components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render = { path = "../render" }
bytemuck = "1.12.3"
egui_winit_vulkano = "0.24.0"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
cgmath = { version = "0.18.0" }
eframe = "0.21.0"
